name: Android CI

on:
  push:
    branches: [ "react" ]
  pull_request:
    branches: [ "react" ]
  workflow_dispatch:
    description: Run it
jobs:
    android:
      name: Build for Android
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Initialize repo
        run: |
          git config --global user.name "sounddrill31"
          git config --global user.email "sounddrill31@gmail.com"
        id: pwd
      - name: Grant execute permission for gradlew
        run: |
          cd android && chmod +x gradlew
          npm install --legacy-peer-deps
      - name: Build with Gradle
        run: cd android && ./gradlew assembleDebug #assembleDebug assembleRelease
      - name: Sign apk
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        #env:
          #BUILD_TOOLS_VERSION: "33.0.2"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: App-Artifact
            path: |
              app/build/outputs/apk/*/*.apk
            #  ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Upload to Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: |
            app/build/outputs/apk/*/*.apk
            #  ${{steps.sign_app.outputs.signedReleaseFile}}
          name: ${{ github.pull_request_target }} ${{ github.GITHUB_BASE_REF }} ${{ github.run_id }}
          tag_name: react
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
