name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    description: Run it
jobs:
    android:
      name: Build for Android
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Initialize repo
        run: |
          git config --global user.name "sounddrill31"
          git config --global user.email "sounddrill31@gmail.com"
        id: pwd
      - name: Grant execute permission for gradlew
        run: |
          cd android && chmod +x gradlew
          npm install --legacy-peer-deps && cd android 
      - name: Build with Gradle
        run: ./gradlew assembleDebug #assembleDebug assembleRelease
        id: test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: App-Artifact
            path: |
              app/build/outputs/apk/*/*.apk
     #       ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Upload to Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: |
            app/build/outputs/apk/*/*.apk
      #    ${{steps.sign_app.outputs.signedReleaseFile}}
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #job2:
  #  - name: Build for IOS

