name: Android CI

on:
  push:
    branches: [ "kotlin" ]
  pull_request:
    branches: [ "kotlin" ]
  workflow_dispatch:
    description: Run it
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Initialize repo
      run: |
        git config --global user.name "sounddrill31"
        git config --global user.email "sounddrill31@gmail.com"
      id: pwd
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      #run: ./gradlew assembleRelease
      #run: ./gradlew assembleDebug
   # - name: Build with FastLane
   #   run: |
    #    sudo gem install fastlane
    #    bundle exec fastlane beta
   #     sudo apt update
   #     sudo apt install gnupg2 -y
   #     sudo chmod +rwx /var/lib/gems/ --recursive
   #     sudo chmod +rwx /home/runner/work/untitled-upi-for-android-4/untitled-upi-for-android-4 --recursive
   #     sudo chown -R $USER /var/lib/gems/
   #     sudo chown -R $USER /home/runner/work/untitled-upi-for-android-4/untitled-upi-for-android-4
   #      gem install bundler
   #     bundle update
      #  bundle exec fastlane beta
     #   fastlane beta

    - name: Sign apk
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/debug
        signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      #env:
        #BUILD_TOOLS_VERSION: "33.0.2"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: App-Artifact
          path: |
            app/build/outputs/apk/*/*.apk
          #  ${{steps.sign_app.outputs.signedReleaseFile}}
    - name: Upload to Release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: |
          app/build/outputs/apk/*/*.apk
        #  ${{steps.sign_app.outputs.signedReleaseFile}}
        name: ${{ github.pull_request_target }} ${{ github.GITHUB_BASE_REF }} ${{ github.run_id }}
        tag_name: kotlin ${{ github.run_id }} ${{ github.pull_request_target }}
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
