name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    description: Run it
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Initialize repo
      run: |
        git config --global user.name "sounddrill31"
        git config --global user.email "sounddrill31@gmail.com"
      id: pwd

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #- name: Decode Keystore
    #  id: decode_keystore
    #  uses: timheuer/base64-to-file@v1.2
    #  with:
    #    fileName: 'android_keystore.jks'
    #    fileDir: app/keystore/
    #    encodedString: ${{ secrets.KEYSTORE }}
    - name: Build with Gradle
      run: ./gradlew assembleDebug #assembleDebug #assembleRelease #--debug
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    #- name: Sign apk
     # uses: r0adkll/sign-android-release@v1
      #id: test
      #with:
      #  releaseDirectory: app/build/outputs/apk/release
      #  signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
      #  alias: ${{ secrets.ALIAS }}
      #  keyStorePassword: ${{ secrets.KEYSTOREPASSWORD}}
      #  keyPassword: ${{ secrets.KEY_PASSWORD }}
      #env:
      #  BUILD_TOOLS_VERSION: "30.0.2"
    #- name: Build Signed APK
    # uses: victorbnl/build-signed-apk@main
    #  with:
    #    keystore_b64: ${{ secrets.keystore }}
    #    keystore_password: ${{ secrets.key_store_password }}
    #    key_alias: ${{ secrets.key_alias }}
    #    key_password: ${{ secrets.key_password }}
    - name: Sign Apk
      run: |
        jarsigner -keystore app/keystore/android_keystore.jks  -storepass ${{ secrets.key_store_password }} -keypass ${{ secrets.key_password }} app/build/outputs/apk/*/*.apk ${{ secrets.key_alias }}
     #   apksigner sign --ks release.jks app.apk
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: App-Artifact
          path: |
            app/build/outputs/apk/*/*.apk
     #       ${{steps.sign_app.outputs.signedReleaseFile}}
    - name: Upload to Release
      uses: xresloader/upload-to-github-release@v1
      with:
        file: |
          app/build/outputs/apk/*/*.apk
      #    ${{steps.sign_app.outputs.signedReleaseFile}}
        name: ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
